export default function FeesPage() {
  return (
    <div className="min-h-screen p-4 md:p-8">
      <div className="max-w-3xl mx-auto space-y-6">
        <h1 className="typo-title text-2xl">Platform Fees</h1>
        <div className="space-y-4 typo-body text-muted-foreground">
          <p>
            launchpad.fun is a curated token launchpad on Solana. We charge minimal fees to maintain
            the platform, ensure quality curation, and provide a seamless experience for both
            creators and traders.
          </p>

          <h2 className="typo-subtitle text-foreground">Token Launch Application</h2>
          <p>
            Submitting an application to launch a token on launchpad.fun is free. Our team reviews
            all applications to ensure quality and legitimacy. Approved projects may have
            launch-specific fees determined during the application process.
          </p>

          <h2 className="typo-subtitle text-foreground">Trading Fees</h2>
          <p>
            A small fee is charged on each trade to support platform operations, ongoing curation,
            and creator rewards. A portion of trading fees is used to buy back $TOKEN from the
            open market.
          </p>

          <h2 className="typo-subtitle text-foreground">Creator Rewards</h2>
          <p>
            Approved token creators earn a portion of trading fees generated by their token.
            Rewards accrue automatically and can be claimed from your profile page.
          </p>

          <h2 className="typo-subtitle text-foreground">Network Fees</h2>
          <p>
            All transactions on Solana require a small network fee (typically less
            than $0.01). These fees go to Solana validators, not launchpad.fun.
          </p>
        </div>
      </div>
    </div>
  );
}
